### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by abusalaa7** [JeringTech/Javascript.NodeJS#78]
If I understand it correctly, the [NodeJsProcessOptions](https://github.com/JeringTech/Javascript.NodeJS#nodejsprocessoptions) configures the singleton service that communicates with the out of process node service via http. Is that correct? The name "NodeJsProcessOptions" implies that this is an alternative way to spawning an out of process node instance by running an in-process one. Which I'm assuming is not correct? This library doesn't have a way of running node in process?

**Comment by JeremyTCD** [comment]
[OutOfProcessNodeJSServiceOptions](https://github.com/JeringTech/Javascript.NodeJS#outofprocessnodejsserviceoptions) configures the service. NodeJsProcessOptions configures the Node.js processes spawned .

Anyway you're right, this library doesn't provide a way to run Node.js in process. The reason for the naming scheme is that we intend to provide an in-process alternative if/when Node.js gets an [official embedding API](https://github.com/nodejs/node/issues/23265).  

There is a library, [Edge.js](https://tjanczuk.github.io/edge/), that allows you to run Node.js in process. It's a valiant attempt, unfortunately we had issues with it:

- It's stuck on an old Node.js release. This is because Edge.js uses customized Node.js binaries.
- It limits you to one Node.js instance (not safe to host several in a process). Coupled with the dated Node.js binary, options for concurrency are limited.
- Limited to .NET Framework (as far as invoking in Node.js from C# goes).

If those aren't issues for you, do consider it.  

Thanks for bringing this up, will add a note in the documentation.

**Comment by abusalaa7** [comment]
Thanks for clarifying.
